permalink: /:categories/:title/

port: 4000
pygments: true
url: http://mccst.com
markdown: kramdown
title : McCormick Stevenson Corporation
author: McCormick Stevenson Corporation

authors:
  noel:
    display_name: Noel McCormick
    image: noel.jpg
    twitter: WNMcCormick
    bio: ""
